# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notificacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notificacion(object):
    def setupUi(self, Notificacion):
        Notificacion.setObjectName("Notificacion")
        Notificacion.resize(400, 187)
        Notificacion.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"}\n"
"\n"
"QWidget{\n"
"background: qlineargradient(spread:pad, x1:1, y1:0.739, x2:1, y2:0.25, stop:0 rgba(37, 83, 134, 255), stop:1 rgba(29, 29, 29, 255))\n"
"\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"background: #1d1d1d;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background: #2d89ef;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"background:  #2b5797;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:#1d1d1d;\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #2d89ef;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2b5797;\n"
"color: white;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QGroupBox{\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QGroupBox#ref{\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#Titulo\n"
"{\n"
"font-size:20px;\n"
"}\n"
"QTableWidget\n"
"{\n"
"color:white;\n"
"text-align:center;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Notificacion)
        self.frame.setGeometry(QtCore.QRect(10, 20, 381, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Titulo = QtWidgets.QLabel(self.frame)
        self.Titulo.setGeometry(QtCore.QRect(150, 0, 121, 41))
        self.Titulo.setObjectName("Titulo")
        self.l_texto = QtWidgets.QLabel(self.frame)
        self.l_texto.setGeometry(QtCore.QRect(20, 40, 341, 71))
        self.l_texto.setObjectName("l_texto")
        self.b_analizar = QtWidgets.QPushButton(Notificacion)
        self.b_analizar.setGeometry(QtCore.QRect(90, 160, 75, 23))
        self.b_analizar.setObjectName("b_analizar")
        self.b_aceptar = QtWidgets.QPushButton(Notificacion)
        self.b_aceptar.setGeometry(QtCore.QRect(177, 160, 75, 23))
        self.b_aceptar.setObjectName("b_aceptar")
        self.b_detener = QtWidgets.QPushButton(Notificacion)
        self.b_detener.setGeometry(QtCore.QRect(260, 160, 75, 23))
        self.b_detener.setObjectName("b_detener")

        self.retranslateUi(Notificacion)
        self.b_aceptar.clicked.connect(Notificacion.close)
        QtCore.QMetaObject.connectSlotsByName(Notificacion)

    def retranslateUi(self, Notificacion):
        _translate = QtCore.QCoreApplication.translate
        Notificacion.setWindowTitle(_translate("Notificacion", "Dialog"))
        self.Titulo.setText(_translate("Notificacion", "Informe"))
        self.l_texto.setText(_translate("Notificacion", "El token "))
        self.b_analizar.setText(_translate("Notificacion", "Analizar"))
        self.b_aceptar.setText(_translate("Notificacion", "Aceptar"))
        self.b_detener.setText(_translate("Notificacion", "Detener"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Notificacion = QtWidgets.QDialog()
    ui = Ui_Notificacion()
    ui.setupUi(Notificacion)
    Notificacion.show()
    sys.exit(app.exec_())
