# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tokens.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(733, 488)
        Dialog.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"}\n"
"\n"
"QWidget#Dialog{\n"
"background: qlineargradient(spread:pad, x1:1, y1:0.739, x2:1, y2:0.25, stop:0 rgba(37, 83, 134, 255), stop:1 rgba(29, 29, 29, 255))\n"
"\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"background: #1d1d1d;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background: #2d89ef;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"background:  #2b5797;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:#1d1d1d;\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #2d89ef;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2b5797;\n"
"color: white;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QGroupBox{\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QGroupBox#ref{\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#Titulo\n"
"{\n"
"font-size:20px;\n"
"}\n"
"QTableWidget\n"
"{\n"
"color:white;\n"
"text-align:center;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 691, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Titulo = QtWidgets.QLabel(self.frame)
        self.Titulo.setGeometry(QtCore.QRect(170, 0, 321, 41))
        self.Titulo.setObjectName("Titulo")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(30, 290, 621, 51))
        self.groupBox.setObjectName("groupBox")
        self.L_notif = QtWidgets.QLabel(self.groupBox)
        self.L_notif.setGeometry(QtCore.QRect(10, 13, 381, 21))
        self.L_notif.setText("")
        self.L_notif.setObjectName("L_notif")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 40, 611, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.L_token = QtWidgets.QLabel(self.groupBox_2)
        self.L_token.setGeometry(QtCore.QRect(10, 25, 101, 16))
        self.L_token.setObjectName("L_token")
        self.B_scrap = QtWidgets.QPushButton(self.groupBox_2)
        self.B_scrap.setGeometry(QtCore.QRect(500, 26, 75, 23))
        self.B_scrap.setObjectName("B_scrap")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(97, 24, 231, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.B_fav = QtWidgets.QPushButton(self.groupBox_2)
        self.B_fav.setGeometry(QtCore.QRect(350, 26, 121, 23))
        self.B_fav.setObjectName("B_fav")
        self.B_detener = QtWidgets.QPushButton(self.frame)
        self.B_detener.setGeometry(QtCore.QRect(260, 370, 75, 23))
        self.B_detener.setObjectName("B_detener")
        self.B_cerrar = QtWidgets.QPushButton(self.frame)
        self.B_cerrar.setGeometry(QtCore.QRect(350, 370, 75, 23))
        self.B_cerrar.setObjectName("B_cerrar")
        self.B_guardar = QtWidgets.QPushButton(self.frame)
        self.B_guardar.setGeometry(QtCore.QRect(60, 370, 171, 23))
        self.B_guardar.setObjectName("B_guardar")
        self.T_Tokens = QtWidgets.QTableWidget(self.frame)
        self.T_Tokens.setGeometry(QtCore.QRect(20, 110, 621, 171))
        self.T_Tokens.setObjectName("T_Tokens")
        self.T_Tokens.setColumnCount(6)
        self.T_Tokens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_Tokens.setHorizontalHeaderItem(5, item)
        self.L_CellSelected = QtWidgets.QLabel(self.frame)
        self.L_CellSelected.setGeometry(QtCore.QRect(500, 390, 47, 13))
        self.L_CellSelected.setText("")
        self.L_CellSelected.setObjectName("L_CellSelected")
        self.L_CellChanged = QtWidgets.QLabel(self.frame)
        self.L_CellChanged.setGeometry(QtCore.QRect(0, 0, 47, 13))
        self.L_CellChanged.setText("")
        self.L_CellChanged.setObjectName("L_CellChanged")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(630, 470, 91, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.B_cerrar.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Titulo.setText(_translate("Dialog", "Seguimiento de criptomonedas"))
        self.groupBox.setTitle(_translate("Dialog", "Notificaciones"))
        self.groupBox_2.setTitle(_translate("Dialog", "Token"))
        self.L_token.setText(_translate("Dialog", "Insertar Token:"))
        self.B_scrap.setText(_translate("Dialog", "Scrap"))
        self.B_fav.setText(_translate("Dialog", "Favoritos"))
        self.B_detener.setText(_translate("Dialog", "Detener"))
        self.B_cerrar.setText(_translate("Dialog", "Cerrar"))
        self.B_guardar.setText(_translate("Dialog", "Guardar punto de referencia"))
        item = self.T_Tokens.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.T_Tokens.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Simbolo"))
        item = self.T_Tokens.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        item = self.T_Tokens.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Referencia"))
        item = self.T_Tokens.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Variacion"))
        item = self.T_Tokens.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Tiempo"))
        self.label_4.setText(_translate("Dialog", "Facundo Farias"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
